runtime: go
api_version: go1
service: fundue-collider

handlers:
- url: /.*
  script: _go_app
  secure: always

env_variables:
  BYPASS_JOIN_CONFIRMATION: false
  # Only change these while developing, do not commit to source!
  # Use appcfg.py --env_variable=ICE_SERVER_API_KEY:KEY \
  # in order to replace variables when deploying.
  ICE_SERVER_API_KEY: none

resources:
  cpu: 2
  memory_gb: 1
  disk_size_gb: 10
